### ISSUE TITLE
Display FW_CODE along with FW_VERSION

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-LCD-ESP32-LIB#1]
@moinmoin-sh I have added these constants to each of the firmwares at the top of the sketches. The version is just used for display purposes but the `FW_CODE` is used to generate the MQTT client id (e.g. `<FW_CODE>-<MAC_ADDRESS>`).

Currently you have `URC` hardcoded in the LCD library - it might be good to pass `FW_CODE` along with `FW_VERSION` when initialising the LCD and using this instead?

**Comment by moinmoin-sh** [comment]
You're right. This is one of the left overs from the OLED lib. So we're going to pass 2 parameters to draw_logo(FW_CODE, FW_VERSION)

**Comment by sumnerboy12** [comment]
Yeah - or potentially `FW_NAME` (would need to be added) to be more 
descriptive?

Would be nice to see `OXRS-SHA-StateMonitor-ESP32-FW` pop up to make it 
very clear what is running.

**Comment by moinmoin-sh** [comment]
I basically agree, but there is limited width on the display. I'm using mostly mono (fixed width) fonts for structured and predictable display. For Name and Version a proportional font coud be used to be able to display more characters per line. Name and version should not use more that one line on the display and also the font shouldn't be smaller. Need to test how long the string can be

**Comment by sumnerboy12** [comment]
Yes - agree - could it scroll?

**Comment by moinmoin-sh** [comment]
Scrolling is not delivered by the lib. The disadvantage I see is that scrolling would require permanet display updates (SPI data transfer) . This increases the loop time (= decreases the scan rate of the MCP's) which in turn effects responsitivity and debouncing.

An alternative could be to show the full version string at startup and replace it later on with the structured screen

**Comment by sumnerboy12** [comment]
Ok - lets see how long it can be - open to suggestions for the best way forward - you know this stuff better than me!
