### ISSUE TITLE
IP address not displaying when network connected after startup with no network

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-LCD-ESP32-LIB#10]
Been testing failover handling. Noticed today if I start a device with no network, it will display 0.0.0.0 with the red link status led. If I then plug in the ethernet cable the link status turns green but the IP address stays 0.0.0.0, even though the device has connected and has received a DHCP lease etc.

I think this is because the `_ethernet->linkStatus()` updates to `LinkON` before an IP address has been obtained by DHCP. So in `OXRS_LCD.cpp` on line 390ish your code detects the change in link status and updates the display, but the IP address is still 0.0.0.0. And then once the IP address is assigned, the link status doesn't change, meaning the UI is never updated.

**Comment by moinmoin-sh** [comment]
I can't reproduce this behavior with my setup. Probably my router is faster/different?
This PR should take care for it, please test and let me know.
