### ISSUE TITLE
Unable to compile (missing #define in User_Setup.h)

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-LCD-ESP32-LIB#2]
Documentation fix for the README I think - your example is potentially missing the following;
```
#define LOAD_GFXFF
```
Without this I couldn't get it to compile.

@moinmoin-sh

**Comment by moinmoin-sh** [comment]
this is defined by default here : https://github.com/Bodmer/TFT_eSPI in User_Setup.h line 301 as part of the TFE_eSPI lib

**Comment by sumnerboy12** [comment]
I see - I thought I was supposed to replace the entire contents of `User_Setup.h` with the snippet you posted in the README. 

That is a big file to scan and find the bits that need to be updated to for the RACK32. I think others will likely have problems with this. 

Could we provide a full version of the file to use for the RACK32 in this repo?

**Comment by moinmoin-sh** [comment]
I struggled also with that and the README was more or less a kind of minimal information. Just to say "I told you ..."
TFT_eSPI lib offers a possibility of simplified user setups. Need to dig deeper into that to deliver what you suggested.

**Comment by sumnerboy12** [comment]
Ok - even if you just add a link to the relevant docs for that library 
to give someone a head start on where to begin?

That would be enough, otherwise we are going to get loads of questions 
from people about how to get this compiling.

**Comment by moinmoin-sh** [comment]
Did you see the changes in my repro regarding user_setup ?

**Comment by sumnerboy12** [comment]
Yeah and they worked great. Much better option i think, easy to follow.
