### ISSUE TITLE
Hide ethernet/wifi icon if no network detected

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-LCD-ESP32-LIB#26]
If I pull the ethernet plug out of my Rack32 it looks a bit weird with a red LED, no IP address, and then the ethernet icon.

**Comment by moinmoin-sh** [comment]
I would like to have the icon because it shows which connection (eth/wifi) we are waiting for.
what about this proposal:
![grafik](https://user-images.githubusercontent.com/53935853/146588873-0677828e-3d1f-4502-9385-f4f99f3f5fde.png)

**Comment by sumnerboy12** [comment]
Would it be possible to replace the LED with the icon, and colour the icon green/red depending on state?

**Comment by sumnerboy12** [comment]
Or even just moving it from where you have it in the screenshot above, to be between the `IP` and `:`?

`IP <icon>:`

That might look better, with the text all left-aligned properly.

**Comment by moinmoin-sh** [comment]
I would prefer the way how it's shown in my proposal above.
The "LED" shows the status of the physical link (eth/wifi) so the LED and the icon belong to each other. An IP can only be gotten after the conection is established and the label IP and the numeric also belong to eaxh other. Sounds logic to me.

**Comment by sumnerboy12** [comment]
Up to you. Maybe we could post the two options in discord and have a vote?

Will leave with you to decide.

**Comment by moinmoin-sh** [comment]
made the decission to release the proposal above. PR issued
