### ISSUE TITLE
Have special handling to display "OXRS Core Team" in "MAKER" display when code is "IO"

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-LCD-ESP32-LIB#8]
Think we need a better display for firmware written by the core team, rather than "MAKER: IO".

Can we have a special translation for that code so we get "MAKER: OXRS Core Team"?

**Comment by moinmoin-sh** [comment]
That would mean we are breaking our own rules

**Comment by sumnerboy12** [comment]
It does, but showing "IO" doesn't seem very useful or accurate. Every other
maker code is related to the company or person. But IO has no meaning.

**Comment by moinmoin-sh** [comment]
I agree, just wanted your confirmation.

Should we try to convince the Core Team to change the maker code to something more meaningfull. I don't know what `IO` stands for.

**Comment by sumnerboy12** [comment]
It should be OXRS really, but then the firmware would be OXRS-OXRS-Etc...

So we decided to use IO since the website is oxrs.io.

Maybe just change IO to OXRS on screen?

**Comment by moinmoin-sh** [comment]
To me OXRS in the MAKER context is also not very nice.

I think we should procedd with your first suggestion : `Maker : OXRS Core Team` . I don't expect any complains.

**Comment by sumnerboy12** [comment]
Perhaps we have a lookup in the library, similar to the icon lookup, so
each code is translated to the maker name?

If no entry in the lookup, default to the code.

**Comment by moinmoin-sh** [comment]
I had that in mind but it contradicts the requirement of a "dump" library that you proposed in the other discussion. It would require permanet maintenance. 
Long term I would like to take the logo off the lib and transfer the responsibility to the FW. I don't have a solution for that so far and it was much easier to implement it in the lib. Not code wise, but generating the bitmap is tricky.
Not a problem as long as we have just a handfull of makers - which would also be true for the name translation.
A (temporary) solution to be implemented in the lib could be : 
- take this table https://oxrs.io/glossary/makers.html for Maker (Designator)-> Owner translation
- if Maker not listed -> show maker code
- use logo as available (selected by maker code)
- if not available -> show OXRS bitmap

**Comment by sumnerboy12** [comment]
Yeah that is pretty much exactly what I had in mind. Think that will be fine in the short/medium term.

**Comment by moinmoin-sh** [comment]
I started playing with the maker name (Owner) display.
It turns out that the space behind `Maker :` is too small to display `SuperHouse Automation` as one of the longest. 
I propose : 
- if maker is listed -> print the Owner name only (without `Maker `: in front)
- if maker NOT listed -> print as we do now `Maker : XYZ`
A smaller font is in favour of readability no option

see PR in LCD lib
